"""Embedder protocol and helpers for VectorStorePipeline.

Usage::

    from ragdoc.pipeline import VectorStorePipeline, EmbedderConfig, prompt_content_text

    vs = VectorStorePipeline(
        pipeline=doc_pipeline,
        vector_store=qdrant_store,
        embedders={
            # Dense: embed the focused semantic summary
            "dense": EmbedderConfig(my_dense_embedder),
            # Sparse: embed the full document text for keyword recall
            "sparse": EmbedderConfig(my_sparse_embedder, text_fn=prompt_content_text),
        },
    )
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from ragdoc.chunking.chunk import Chunk


@runtime_checkable
class Embedder(Protocol):
    """Protocol for async embedding models."""

    async def embed(self, texts: list[str]) -> list[list[float]]:
        """Embed *texts* and return one vector per input, in order."""
        ...


@dataclass
class EmbedderConfig:
    """Pairs an :class:`Embedder` with the text-extraction strategy for a chunk.

    Args:
        embedder: The embedding model to use.
        text_fn:  Callable that extracts the text to embed from a :class:`~ragdoc.chunking.Chunk`.
                  Defaults to :func:`embedding_content_text` (the focused semantic content).
    """

    embedder: Embedder
    text_fn: Callable[[Chunk], str] = field(default=lambda chunk: chunk.embedding_content)


def embedding_content_text(chunk: Chunk) -> str:
    """Extract ``embedding_content`` from a chunk.

    This is the default text for dense embedders.  ``embedding_content`` is produced
    by the chunker specifically as a focused semantic representation:

    * :class:`~ragdoc.chunking.LLMChunker` — a topic summary generated by an LLM.
    * :class:`~ragdoc.chunking.SimpleChunker` — the rendered document text.

    Dense models benefit from this focused signal.
    """
    return chunk.embedding_content


def prompt_content_text(chunk: Chunk) -> str:
    """Extract ``prompt_content`` from a chunk.

    Use this as ``text_fn`` for sparse or keyword-based embedders (e.g. BM25, SPLADE).
    ``prompt_content`` is the full, uncompressed document text.  Sparse/keyword models
    rely on exact term overlap and benefit from the broader vocabulary in the full text,
    whereas dense models are better served by the focused ``embedding_content``.
    """
    return chunk.prompt_content
